//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.AuditBigData
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// AuditOperationType.
    /// </summary>
    // *** Start programmer edit section *** (AuditOperationType CustomAttributes)

    // *** End programmer edit section *** (AuditOperationType CustomAttributes)
    public enum AuditOperationType
    {
        
        // *** Start programmer edit section *** (AuditOperationType.Insert CustomAttributes)

        // *** End programmer edit section *** (AuditOperationType.Insert CustomAttributes)
        Insert,
        
        // *** Start programmer edit section *** (AuditOperationType.Update CustomAttributes)

        // *** End programmer edit section *** (AuditOperationType.Update CustomAttributes)
        Update,
        
        // *** Start programmer edit section *** (AuditOperationType.Delete CustomAttributes)

        // *** End programmer edit section *** (AuditOperationType.Delete CustomAttributes)
        Delete,
        
        // *** Start programmer edit section *** (AuditOperationType.Select CustomAttributes)

        // *** End programmer edit section *** (AuditOperationType.Select CustomAttributes)
        Select,
        
        // *** Start programmer edit section *** (AuditOperationType.Execute CustomAttributes)

        // *** End programmer edit section *** (AuditOperationType.Execute CustomAttributes)
        Execute,
        
        // *** Start programmer edit section *** (AuditOperationType.SessionStart CustomAttributes)

        // *** End programmer edit section *** (AuditOperationType.SessionStart CustomAttributes)
        SessionStart,
        
        // *** Start programmer edit section *** (AuditOperationType.SessionEnd CustomAttributes)

        // *** End programmer edit section *** (AuditOperationType.SessionEnd CustomAttributes)
        SessionEnd,

        // *** Start programmer edit section *** (AuditOperationType.Ratify CustomAttributes)

        // *** End programmer edit section *** (AuditOperationType.Ratify CustomAttributes)
        Ratify,

        // *** Start programmer edit section *** (AuditOperationType.Custom CustomAttributes)

        // *** End programmer edit section *** (AuditOperationType.Custom CustomAttributes)
        Custom,
    }
}
