//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewPlatform.Flexberry.AuditBigData
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// ExecutionStatus.
    /// </summary>
    // *** Start programmer edit section *** (ExecutionStatus CustomAttributes)

    // *** End programmer edit section *** (ExecutionStatus CustomAttributes)
    public enum ExecutionStatus
    {
        
        // *** Start programmer edit section *** (ExecutionStatus.Unknown CustomAttributes)

        // *** End programmer edit section *** (ExecutionStatus.Unknown CustomAttributes)
        Unknown,
        
        // *** Start programmer edit section *** (ExecutionStatus.Unexecuted CustomAttributes)

        // *** End programmer edit section *** (ExecutionStatus.Unexecuted CustomAttributes)
        Unexecuted,
        
        // *** Start programmer edit section *** (ExecutionStatus.Executed CustomAttributes)

        // *** End programmer edit section *** (ExecutionStatus.Executed CustomAttributes)
        Executed,
        
        // *** Start programmer edit section *** (ExecutionStatus.Failed CustomAttributes)

        // *** End programmer edit section *** (ExecutionStatus.Failed CustomAttributes)
        Failed,
    }
}
